#!/usr/bin/env python3

"""
Setup and manage residential proxy for My Toolkit.

This script helps configure a Squid-based residential proxy forwarder
that routes traffic through a residential proxy provider (e.g., DataImpulse).
"""

import argparse
import sys
import subprocess
from pathlib import Path
from typing import Optional
import json

try:
    import requests
except ImportError:
    print("Error: requests is not installed")
    sys.exit(1)


class Config:
    """Proxy configuration paths"""

    TOOLKIT_CONFIG_DIR = Path.home() / ".config" / "my-toolkit"
    PROXY_CONFIG_FILE = TOOLKIT_CONFIG_DIR / "proxy.json"
    SQUID_CONFIG_FILE = TOOLKIT_CONFIG_DIR / "squid.conf"

    # Default settings
    DEFAULT_LOCAL_PORT = 3128
    DEFAULT_TIMEOUT = 5


class ProxyManager:
    """Manage residential proxy configuration"""

    def __init__(self):
        self.config = Config()
        self.config.TOOLKIT_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    def load_config(self) -> dict:
        """Load proxy configuration"""
        if not self.config.PROXY_CONFIG_FILE.exists():
            return {}

        try:
            with open(self.config.PROXY_CONFIG_FILE, 'r') as f:
                return json.load(f)
        except Exception as e:
            print(f"Warning: Failed to load config: {e}")
            return {}

    def save_config(self, config: dict):
        """Save proxy configuration"""
        try:
            with open(self.config.PROXY_CONFIG_FILE, 'w') as f:
                json.dump(config, f, indent=2)
            # Protect credentials
            self.config.PROXY_CONFIG_FILE.chmod(0o600)
            print(f"✓ Configuration saved to: {self.config.PROXY_CONFIG_FILE}")
        except Exception as e:
            print(f"Error: Failed to save config: {e}")
            sys.exit(1)

    def generate_squid_conf(self, proxy_host: str, proxy_port: int,
                           proxy_user: str, proxy_pass: str,
                           local_port: int = 3128) -> str:
        """Generate Squid configuration"""

        # Use user-space directories
        cache_dir = Path.home() / ".cache" / "my-toolkit" / "squid"
        log_dir = cache_dir / "logs"

        config = f"""# Squid configuration for My Toolkit residential proxy
# Generated by proxy-setup.py

# PID file (systemd manages this)
pid_filename {cache_dir}/squid.pid

# Network settings
http_port {local_port}

# Access control
acl localnet src 127.0.0.1
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

# Deny requests to certain unsafe ports
http_access deny !Safe_ports

# Deny CONNECT to other than secure SSL ports
http_access deny CONNECT !SSL_ports

# Only allow localhost connections
http_access allow localnet
http_access deny all

# Logging (user-space)
access_log stdio:{log_dir}/access.log
cache_log {log_dir}/cache.log

# Cache settings (disabled - forwarding proxy only)
cache deny all
cache_mem 0 MB

# Residential proxy configuration
cache_peer {proxy_host} parent {proxy_port} 0 no-query no-digest no-netdb-exchange connect-fail-limit=0 connect-timeout=1 default login={proxy_user}:{proxy_pass}
never_direct allow all

# Timeouts
connect_timeout 10 seconds
read_timeout 300 seconds
request_timeout 300 seconds
"""
        return config

    def configure(self, residential_proxy_url: str, local_port: int = 3128):
        """
        Configure residential proxy

        Args:
            residential_proxy_url: Proxy URL in format http://user:pass@host:port
            local_port: Local port for Squid to listen on
        """
        # Parse proxy URL
        import re
        pattern = r'https?://([^:]+):([^@]+)@([^:]+):(\d+)'
        match = re.match(pattern, residential_proxy_url)

        if not match:
            print("Error: Invalid proxy URL format")
            print("Expected format: http://username:password@host:port")
            sys.exit(1)

        proxy_user, proxy_pass, proxy_host, proxy_port = match.groups()
        proxy_port = int(proxy_port)

        print(f"Configuring residential proxy:")
        print(f"  Provider: {proxy_host}:{proxy_port}")
        print(f"  Local port: {local_port}")
        print(f"  Username: {proxy_user}")
        print("")

        # Generate Squid config
        squid_conf = self.generate_squid_conf(
            proxy_host=proxy_host,
            proxy_port=proxy_port,
            proxy_user=proxy_user,
            proxy_pass=proxy_pass,
            local_port=local_port
        )

        # Create cache and log directories
        cache_dir = Path.home() / ".cache" / "my-toolkit" / "squid"
        log_dir = cache_dir / "logs"
        cache_dir.mkdir(parents=True, exist_ok=True)
        log_dir.mkdir(parents=True, exist_ok=True)
        print(f"✓ Created cache directory: {cache_dir}")

        # Save Squid config
        self.config.SQUID_CONFIG_FILE.write_text(squid_conf)
        self.config.SQUID_CONFIG_FILE.chmod(0o600)
        print(f"✓ Squid configuration saved to: {self.config.SQUID_CONFIG_FILE}")

        # Save metadata
        config = {
            "enabled": True,
            "local_port": local_port,
            "proxy_host": proxy_host,
            "proxy_port": proxy_port,
            "residential_proxy_url": residential_proxy_url,
        }
        self.save_config(config)

        print("\n✓ Proxy configured successfully!")
        print("\nNext steps:")
        print("  1. Enable the proxy service in your NixOS configuration:")
        print("     my-toolkit.services.residential-proxy = true;")
        print("  2. Rebuild your system: sudo nixos-rebuild switch")
        print("  3. Test the proxy: my-toolkit proxy-setup test")

    def test_proxy(self, verbose: bool = False):
        """Test proxy connection"""
        config = self.load_config()

        if not config.get("enabled"):
            print("Error: Proxy not configured. Run: my-toolkit proxy-setup configure")
            sys.exit(1)

        local_port = config.get("local_port", 3128)
        proxy_url = f"http://127.0.0.1:{local_port}"

        print("=" * 60)
        print("Proxy Connection Test")
        print("=" * 60)
        print(f"Local proxy: {proxy_url}")
        print("")

        # Check service status first
        print("0. Checking Squid service status...")
        try:
            result = subprocess.run(
                ["systemctl", "is-active", "residential-proxy"],
                capture_output=True,
                text=True,
                timeout=2
            )
            if result.returncode == 0:
                print(f"   ✓ Service is running")
            else:
                print(f"   ✗ Service is not running")
                print(f"   Start with: sudo systemctl start residential-proxy")
                print(f"   Check logs: journalctl -u residential-proxy -n 50")
                sys.exit(1)
        except FileNotFoundError:
            print(f"   ⚠ Cannot check service status (systemctl not available)")
        except Exception as e:
            print(f"   ⚠ Service check failed: {e}")

        # Test 1: Get local IP (without proxy)
        print("\n1. Getting your server IP...")
        try:
            response = requests.get("https://api.ipify.org", timeout=5)
            local_ip = response.text
            print(f"   ✓ Server IP: {local_ip}")
        except Exception as e:
            print(f"   ✗ Failed: {e}")
            local_ip = None

        # Test 2: Check if proxy port is listening
        print("\n2. Checking if proxy port is listening...")
        try:
            import socket
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(2)
            result = sock.connect_ex(('127.0.0.1', local_port))
            sock.close()
            if result == 0:
                print(f"   ✓ Port {local_port} is listening")
            else:
                print(f"   ✗ Port {local_port} is not listening")
                print(f"   Check Squid logs: journalctl -u residential-proxy")
                sys.exit(1)
        except Exception as e:
            print(f"   ⚠ Port check failed: {e}")

        # Test 3: Get IP through proxy
        print("\n3. Getting IP through residential proxy...")
        try:
            proxies = {
                "http": proxy_url,
                "https": proxy_url,
            }
            response = requests.get("https://api.ipify.org", proxies=proxies, timeout=10)
            proxy_ip = response.text
            print(f"   ✓ Proxy IP: {proxy_ip}")

            if local_ip and proxy_ip != local_ip:
                print(f"   ✓ SUCCESS: IP changed (proxy is working!)")
            elif local_ip:
                print(f"   ✗ WARNING: IP didn't change (proxy may not be working)")
                print(f"   Check your residential proxy credentials in squid.conf")
            else:
                print(f"   ✓ Got IP through proxy: {proxy_ip}")

        except requests.exceptions.ProxyError as e:
            print(f"   ✗ Proxy connection failed: {e}")
            print("\n   Troubleshooting:")
            print("     1. Check if Squid is running: systemctl status residential-proxy")
            print("     2. Check Squid logs: journalctl -u residential-proxy -n 50")
            print("     3. Verify squid.conf syntax: squid -k parse -f ~/.config/my-toolkit/squid.conf")
            print("     4. Test residential proxy directly:")
            print(f"        curl -x {config.get('residential_proxy_url')} https://api.ipify.org")
            sys.exit(1)
        except Exception as e:
            print(f"   ✗ Failed: {e}")
            sys.exit(1)

        # Test 4: Test with YTS (if verbose)
        if verbose:
            print("\n4. Testing with YTS API...")
            import urllib3
            urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

            yts_mirrors = [
                "https://yts.mx/api/v2/list_movies.json",
                "https://yts.lt/api/v2/list_movies.json",
            ]

            success = False
            for mirror_url in yts_mirrors:
                try:
                    proxies = {
                        "http": proxy_url,
                        "https": proxy_url,
                    }
                    response = requests.get(
                        mirror_url,
                        params={"query_term": "test", "limit": 1},
                        proxies=proxies,
                        timeout=10,
                        verify=False
                    )

                    # Check if response is JSON (not ISP block page)
                    content_type = response.headers.get('content-type', '')
                    if 'json' in content_type.lower():
                        data = response.json()
                        if data.get("status") == "ok":
                            domain = mirror_url.split('/')[2]
                            print(f"   ✓ YTS API accessible through proxy ({domain})!")
                            success = True
                            break
                    else:
                        continue
                except Exception:
                    continue

            if not success:
                print(f"   ✗ All YTS mirrors blocked or unreachable")
                print(f"   This may be normal if your residential proxy doesn't route to unblocked IPs")

        print("\n" + "=" * 60)
        print("✓ Proxy test completed successfully!")
        print("\nNext steps:")
        print("  - Run torrent search: my-toolkit torrent-search \"Movie Name\"")
        print("  - Full health check: my-toolkit health-check")
        print("=" * 60)

    def status(self):
        """Show proxy status"""
        config = self.load_config()

        if not config.get("enabled"):
            print("Proxy: Not configured")
            print("\nRun: my-toolkit proxy-setup configure <proxy-url>")
            return

        print("Proxy Configuration:")
        print(f"  Status: Configured")
        print(f"  Provider: {config.get('proxy_host')}:{config.get('proxy_port')}")
        print(f"  Local port: {config.get('local_port', 3128)}")
        print(f"  Config file: {self.config.SQUID_CONFIG_FILE}")
        print("")

        # Check if service is running
        try:
            result = subprocess.run(
                ["systemctl", "is-active", "residential-proxy"],
                capture_output=True,
                text=True
            )
            if result.returncode == 0:
                print("  Service: ✓ Running")
            else:
                print("  Service: ✗ Not running")
                print("  Start with: sudo systemctl start residential-proxy")
        except:
            print("  Service: Unknown (systemctl not available)")

        print("\nEnvironment variables:")
        local_port = config.get("local_port", 3128)
        print(f"  export HTTP_PROXY=http://127.0.0.1:{local_port}")
        print(f"  export HTTPS_PROXY=http://127.0.0.1:{local_port}")

    def disable(self):
        """Disable proxy"""
        config = self.load_config()
        config["enabled"] = False
        self.save_config(config)
        print("✓ Proxy disabled")
        print("\nEnvironment variables are not set automatically.")
        print("Scripts will no longer use the proxy.")


def main():
    parser = argparse.ArgumentParser(
        description="Setup and manage residential proxy for My Toolkit",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Configure with DataImpulse proxy
  proxy-setup.py configure "http://user:pass@gw.dataimpulse.com:823"

  # Configure on custom port
  proxy-setup.py configure "http://user:pass@proxy.example.com:1080" --port 3129

  # Test proxy connection
  proxy-setup.py test

  # Show status
  proxy-setup.py status

  # Disable proxy
  proxy-setup.py disable

Proxy URL format:
  http://username:password@hostname:port

  Example with DataImpulse (with country routing):
  http://YOUR_USER__cr.cy,gr:YOUR_PASS@gw.dataimpulse.com:823

After configuration:
  1. Enable in NixOS config: my-toolkit.services.residential-proxy = true;
  2. Rebuild: sudo nixos-rebuild switch
  3. Test: my-toolkit proxy-setup test

Your scripts will automatically use the proxy when configured.
        """
    )

    subparsers = parser.add_subparsers(dest='command', help='Command to run')

    # Configure command
    configure_parser = subparsers.add_parser('configure', help='Configure residential proxy')
    configure_parser.add_argument('proxy_url', help='Residential proxy URL (http://user:pass@host:port)')
    configure_parser.add_argument('--port', type=int, default=3128, help='Local port for Squid (default: 3128)')

    # Test command
    test_parser = subparsers.add_parser('test', help='Test proxy connection')
    test_parser.add_argument('-v', '--verbose', action='store_true', help='Verbose output with additional tests')

    # Status command
    subparsers.add_parser('status', help='Show proxy status')

    # Disable command
    subparsers.add_parser('disable', help='Disable proxy')

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    manager = ProxyManager()

    if args.command == 'configure':
        manager.configure(args.proxy_url, args.port)
    elif args.command == 'test':
        manager.test_proxy(verbose=args.verbose)
    elif args.command == 'status':
        manager.status()
    elif args.command == 'disable':
        manager.disable()


if __name__ == "__main__":
    main()
